INSERT INTO tb_user(email) VALUES ('carrie@gmail.com');
INSERT INTO tb_user(email) VALUES ('harrison@gmail.com');
INSERT INTO tb_user(email) VALUES ('daisy@gmail.com');
INSERT INTO tb_user(email) VALUES ('natalie@gmail.com');
INSERT INTO tb_user(email) VALUES ('mark@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2, 'Star Wars: Episódio I - A Ameaça Fantasma', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/gNk8UNAumXlfCdtaxDqsQe7ZGlt.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (4.0, 3, 'Star Wars: O Despertar da Força', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8BTsTfln4jlQrLXUBquXJ0ASQy9.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: Os Últimos Jedi', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/5Iw7zQTHVRBOYpA0V6z0yypOPZh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: Episódio II - Ataque dos Clones', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qdmxochWhzDPjrReabmhnTUYQ5Y.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: Uma Nova Esperança IV', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yUiXA68FfQeA8cRBhd0Ao0jIRZt.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars LEGO: Contos Aterrorizantes', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/f53Jujiap580mgfefID0T0g2e17.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: A Ascensão Skywalker', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/SPkEiZGxq5aHWQ2Zw7AITwSEo2.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Han Solo: Uma História Star Wars', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/x27wDu2yYCMQeLpup1CDY2CtL9t.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Rogue One: Uma História Star Wars', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6t8ES1d12OzWyCGxBeDYLHoaDrT.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: Episódio III - A Vingança dos Sith', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/gqbgylPxoM7Y2lEj9KYzfgixdG.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars Rebels: A Fagulha de Uma Rebelião', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/5lERsrmxhb6ggGQZDHe05qeNCnD.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: O Império Contra-Ataca V', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/nJcAQO0zauDTp72SEMcneIDjA7c.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Livro de Boba Fett', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/sjx6zjQI2dLGtEL0HGWsnq6UyLU.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars: O Retorno de Jedi VI', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/iP2tEA2A77qhbhRfcFkiD6WFOqH.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'The Star Wars Holiday Special', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qfgVAwApyHc1CR7KQVAxTLhz8ED.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars LEGO: Especial de Festas', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/1Lhc32P0a62BgMFgd20wXR1osR3.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Star Wars LEGO: A Ameaça Padawan', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hVl0qfLZ5loznDgQ0HxCTZqvZhz.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Clube da Luta', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/hZkgoQYus5vegHoetLkCJzb17zJ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Guerra Mundial Z', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/31VpBgUX5O4Z3dn5ZbX8HLqoXH3.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Harry Potter e as Relíquias da Morte - Parte 1', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/vcrgU0KaNj5mKUCIQSUdiQwTE9y.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Harry Potter e a Pedra Filosofal', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lvOLivVeX3DVVcwfVkxKf0R22D8.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Alice no País das Maravilhas', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/qNdlZgz9yoSJ8f0YxQWfKGPoVV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Animais Fantásticos e Onde Habitam', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/8Qsr8pvDL3s1jNZQ4HK1d1Xlvnh.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'A Teoria de Tudo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kq2MHrRfH6RTfkvyDEmYLmGHE6U.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Último Duelo', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/4LrL40XecjGLRpX5I2gzMTUt04l.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Interestelar', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Contato', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yFkUPqBuUnbhYbQL8VFpTrAT9za.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Duna', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jYEW5xZkZk2WTrdbMGAPFuBqbDc.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Aquaman', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/2cUsDz4TzFYHrKktT1bKHHQ7Cgm.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);